version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/myapp
permissions:
  - object: /home/ubuntu/myapp/scripts/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/rebuild_and_restart.sh  # New script to rebuild and restart
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu


