version: 0.0
os: linux
version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/myapp
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/myapp/scripts/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

