version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.19
    commands:
      - echo "Initializing Go module..."
      - go mod init myapp || true  # Ensures module exists
      - go mod tidy
  build:
    commands:
      - echo "Building Go application..."
      - go build -o myapp
post_build:
  commands:
    - chmod +x scripts/*.sh
artifacts:
  files:
    - myapp
    - appspec.yml
    - scripts/*
    - '**/*.go'
  discard-paths: no

