version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.19
    commands:
      - echo "Installing dependencies..."
      - go mod tidy
  build:
    commands:
      - echo "Building Go application..."
      - go build -o myapp
  post_build:
    commands:
      - echo "Build completed successfully!"
      - chmod +x myapp
artifacts:
  files:
    - myapp
    - appspec.yml
    - scripts/*
    - '**/*.go'
  discard-paths: no
